//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipboardManager {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipboardManager.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Audio ({0} Bytes) 的當地語系化字串。
        /// </summary>
        public static string AudioData {
            get {
                return ResourceManager.GetString("AudioData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Auto Clean-up at ... Seconds (0 to disable) 的當地語系化字串。
        /// </summary>
        public static string AutoCleanAt {
            get {
                return ResourceManager.GetString("AutoCleanAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} - Ver. {1} 的當地語系化字串。
        /// </summary>
        public static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Clear 的當地語系化字串。
        /// </summary>
        public static string ClearHistory {
            get {
                return ResourceManager.GetString("ClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Clear Now 的當地語系化字串。
        /// </summary>
        public static string ClearNow {
            get {
                return ResourceManager.GetString("ClearNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Remember ... Histories 的當地語系化字串。
        /// </summary>
        public static string EnableHistory {
            get {
                return ResourceManager.GetString("EnableHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Data Currently in Clipboard 的當地語系化字串。
        /// </summary>
        public static string ExistsDataCaption {
            get {
                return ResourceManager.GetString("ExistsDataCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Exit 的當地語系化字串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} Files 的當地語系化字串。
        /// </summary>
        public static string FileData {
            get {
                return ResourceManager.GetString("FileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fo&amp;rget 的當地語系化字串。
        /// </summary>
        public static string ForgetHistory {
            get {
                return ResourceManager.GetString("ForgetHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;History 的當地語系化字串。
        /// </summary>
        public static string HistoryMenu {
            get {
                return ResourceManager.GetString("HistoryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Image ({0}x{1}) 的當地語系化字串。
        /// </summary>
        public static string ImageData {
            get {
                return ResourceManager.GetString("ImageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Notify on Clipboard Change 的當地語系化字串。
        /// </summary>
        public static string NotifyChanges {
            get {
                return ResourceManager.GetString("NotifyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Audio ({0} Bytes) 的當地語系化字串。
        /// </summary>
        public static string OnChangeAudioData {
            get {
                return ResourceManager.GetString("OnChangeAudioData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} Files 的當地語系化字串。
        /// </summary>
        public static string OnChangeFileData {
            get {
                return ResourceManager.GetString("OnChangeFileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Image ({0}x{1}) 的當地語系化字串。
        /// </summary>
        public static string OnChangeImageData {
            get {
                return ResourceManager.GetString("OnChangeImageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}...({1} characters more) 的當地語系化字串。
        /// </summary>
        public static string OnChangeTextData {
            get {
                return ResourceManager.GetString("OnChangeTextData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clipboard Changed 的當地語系化字串。
        /// </summary>
        public static string OnChangeTitle {
            get {
                return ResourceManager.GetString("OnChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Empty content 的當地語系化字串。
        /// </summary>
        public static string OnClearDescription {
            get {
                return ResourceManager.GetString("OnClearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clipboard Cleared 的當地語系化字串。
        /// </summary>
        public static string OnClearTitle {
            get {
                return ResourceManager.GetString("OnClearTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Pin 的當地語系化字串。
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 P&amp;inned 的當地語系化字串。
        /// </summary>
        public static string PinnedMenu {
            get {
                return ResourceManager.GetString("PinnedMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;Restore 的當地語系化字串。
        /// </summary>
        public static string RestoreHistory {
            get {
                return ResourceManager.GetString("RestoreHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Run at &amp;Startup 的當地語系化字串。
        /// </summary>
        public static string RunAtStartup {
            get {
                return ResourceManager.GetString("RunAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}... 的當地語系化字串。
        /// </summary>
        public static string TextData {
            get {
                return ResourceManager.GetString("TextData", resourceCulture);
            }
        }
    }
}
