using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Clipboard Tool Ex")]
[assembly: AssemblyDescription("Simple Clipboard Management Tool")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("eXplosive Theorm Lab")]
[assembly: AssemblyProduct("Clipboard Tool Ex")]
[assembly: AssemblyCopyright("(C) Jeremy Lam \"JLChnToZ\", 2018. Licensed under MIT license. Application icon is generated by Android Asset Studio, licensed under CC BY 3.0.")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: ComVisible(false)]

[assembly: Guid("2026725f-bb44-4bdc-a85b-d2326f7ec716")]

[assembly: AssemblyVersion("0.3.0.0")]
[assembly: AssemblyFileVersion("0.3.0.0")]
